---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 1m
  chart:
    spec:
      chart: openebs
      version: '4.3.3'
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 1m
