---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1h
  url: https://openebs.github.io/openebs

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 1m
  chart:
    spec:
      chart: openebs
      version: '4.3.3'
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 5m
