---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1h
  url: https://openebs.github.io/openebs


---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 1h
  chart:
    spec:
      chart: openebs
      version: '4.3.*'
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 1h

  install:
    createNamespace: true
    timeout: 30m

  upgrade:
    timeout: 30m

  values:
    preUpgradeHook:
      enabled: false
    localpv-provisioner:
      analytics:
        enabled: false
      localpv:
        image:
          registry: quay.io/
        basePath: &hostPath /media/pvolume1
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: *hostPath
      helperPod:
        image:
          registry: quay.io/
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
    minio:
      enabled: false
