---

# kustomization for this dir

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/first-cluster/metallb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: namespaces
      namespace: flux-system

---

# configuration directory for helm

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-conf
  namespace: flux-system
spec:
  interval: 5m

  dependsOn:
    - name: metallb
      namespace: flux-system

  path: "./clusters/first-cluster/metallb/metallb-conf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
