---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 5m
  path: "./clusters/first-cluster/metallb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: metallb-system
