---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb-repo
  namespace: flux-system
spec:
  interval: 1h
  url: https://metallb.github.io/metallb

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1m
  chart:
    spec:
      chart: metallb
      version: '0.15.*'
      sourceRef:
        kind: HelmRepository
        name: metallb-repo
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    timeout: 15m
