---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs

---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
