---
creation_rules:
  - path_regex: .*secret.*\.ya?ml$
    encrypted_regex: ^(data|stringData|contents)$
    age: age1fu36rjuh4sqc88a6qnlnxece4f6wvr0l7egl4zpase2rzqazh46q99z3an #pragma: allowlist secret
