---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: ingress
  hostnames:
    - grafana.lan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: prometheus-grafana
          namespace: monitoring
          port: 80
          weight: 1

# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: grafana-ingress
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`grafana.lan`)
#       kind: Rule
#       services:
#         - name: prometheus-grafana
#           port: 80
#
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: external-grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  # client:
  #   tls:
  #     insecureSkipVerify: true
  external:
    url: http://prometheus-grafana.monitoring.svc.cluster.local
    adminPassword:
      name: grafana-admin-credentials
      key: GF_SECURITY_ADMIN_PASSWORD
    adminUser:
      name: grafana-admin-credentials
      key: GF_SECURITY_ADMIN_USER

---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  datasource:
    name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus-kube-prometheus-prometheus:9090/
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
      # tlsSkipVerify: true
    editable: false
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  datasource:
    name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://prometheus-kube-prometheus-alertmanager:9093/
    access: proxy
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus
      # tlsSkipVerify: true
    editable: false
