---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  datasource:
    name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus-kube-prometheus-prometheus:9090/
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
      # tlsSkipVerify: true
    editable: false
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  datasource:
    name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://prometheus-kube-prometheus-alertmanager:9093/
    access: proxy
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus
      # tlsSkipVerify: true
    editable: false
