---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.26.*'
      sourceRef:
        kind: HelmRepository
        name: cnpg

        # because we have a targetNamespace in the flux
        # kustomization
        namespace: cnpg-system
      interval: 1h

  install:
    createNamespace: true
    timeout: 5m

  upgrade:
    timeout: 5m
