---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system

spec:

  interval: 5m
  path: "./clusters/first-cluster/cnpg"
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-system

  targetNamespace: cnpg-system

  dependsOn:

    - name: namespaces
      namespace: flux-system

    - name: openebs
      namespace: flux-system
