---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  selector:
    matchLabels:
      run: podinfo
  replicas: 2
  template:
    metadata:
      labels:
        run: podinfo
    spec:
      containers:
        - name: podinfo
          image: docker.io/stefanprodan/podinfo:latest
          ports:
            - containerPort: 9898

---


apiVersion: v1
kind: Service
metadata:
  name: podinfo-service

spec:

  type: LoadBalancer

  ports:
    - port: 8080
      targetPort: 9898

  selector:
    run: podinfo
