---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 5m
  path: "./clusters/first-cluster/podinfo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
