---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  dependsOn:
    - name: namespaces
  interval: 1m
  url: https://openebs.github.io/openebs
