---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik-repo
  namespace: flux-system
spec:
  interval: 1h
  url: https://traefik.github.io/charts

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: certmanager-repo
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
