---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: flux-system

        # because we have a targetNamespace in the flux
        # kustomization
        # namespace:
      interval: 1h

  install:
    # createNamespace: true
    timeout: 5m

  upgrade:
    timeout: 5m

  values:

    service:
      spec:
        loadBalancerIP: "192.168.2.220"

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`dashboard.kube`)
        entryPoints:
          - web

    providers:
      kubernetesGateway:
        enabled: true

    gateway:
      listeners:
        web:
          namespacePolicy:
            from: All

    metrics:
      prometheus:
        enabled: true
