---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: certmanager
  namespace: ingress
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: '1.19.*'
      sourceRef:
        kind: HelmRepository
        name: certmanager-repo
        namespace: flux-system
      interval: 1h

  install:
    timeout: 5m

  upgrade:
    timeout: 5m

  values:
    crds:
      enabled: true
    extraArgs:
      - "--enable-gateway-api"

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: '39.0.*'
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: flux-system
      interval: 1h

  install:
    timeout: 5m

  upgrade:
    timeout: 5m

  values:

    ingressClass:
      enabled: false

    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false

    api:
      dashboard: true
      insecure: true

    gateway:

      annotations:
        cert-manager.io/issuer: selfsigned-issuer

      listeners:
        web:
          port: 8000
          protocol: HTTP
          namespacePolicy:
            from: All

        websecure:         # HTTPS listener that matches entryPoint `websecure`
          hostname: grafana.lan
          port: 8443
          protocol: HTTPS  # TLS terminates inside Traefik
          namespacePolicy:
            from: All
          certificateRefs:
            - name: grafana-tls

    ports:
      # Defines the HTTP entry point named 'web'
      web:
        port: 8000
        nodePort: 30100
        # Instructs this entry point to redirect all traffic to the 'websecure' entry point
        # http:
        #   redirections:
        #     entryPoint:
        #       to: websecure
        #       scheme: https
        #       permanent: true

      # Defines the HTTPS entry point named 'websecure'
      websecure:
        port: 8443
        nodePort: 30101

    service:
      spec:
        loadBalancerIP: "192.168.2.220"

    metrics:
      prometheus:
        enabled: true
