---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '81.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

      interval: 5m

  install:
    # createNamespace: true
    timeout: 5m
    crds: CreateReplace

  upgrade:
    timeout: 5m
    crds: CreateReplace

  values:

    crds:
      upgradeJob:
        enabled: true

    grafana:
      enabled: true

      extraLabels:
        app: grafana

      admin:
        existingSecret: grafana-admin-credentials  # pragma: allowlist secret
        userKey: GF_SECURITY_ADMIN_USER
        passwordKey: GF_SECURITY_ADMIN_PASSWORD  # pragma: allowlist secret

      forceDeployDatasources: true
      forceDeployDashboards: true
      defaultDashboardsEnabled: true
      operator:
        dashboardsConfigMapRefEnabled: true
        matchLabels:
          app: grafana

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: monitoring

spec:
  interval: 10m
  chart:
    spec:
      chart: grafana-operator
      version: '5.21.*'
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
      interval: 5m

  install:
    timeout: 5m
    crds: CreateReplace

  upgrade:
    timeout: 5m
    crds: CreateReplace

  values:
    crds:
      immutable: false
    namespaceScope: true
    rbac:
      create: true
    serviceAccount:
      create: true
