---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system

spec:

  interval: 5m
  path: "./clusters/first-cluster/monitoring"
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:

    - name: namespaces
      namespace: flux-system
