---
kind: Secret
apiVersion: v1
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: grafana  # pragma: allowlist secret

type: Opaque
