---

- name: reboot
  hosts: all
  become: true
  tasks:

    - name: Shutdown
      ansible.builtin.command:
        cmd: /sbin/shutdown -r now

    - name: Wait to go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped
