---

- name: proxmox 9 update
  hosts: all
  become: true
  tasks:

    - name: backup /etc/apt
      ansible.builtin.shell: "cp -r /etc/apt /root/etc-apt.bak-$(date +%s)"

    - name: remove all repos
      ansible.builtin.shell: find /etc/apt -type f \( -name "*.list" -o -name "*.sources" \) -delete

    - name: make sure repos are present
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - "deb http://ftp.it.debian.org/debian trixie main contrib non-free-firmware"
        - "deb http://ftp.it.debian.org/debian trixie-updates main contrib non-free-firmware"
        - "deb http://security.debian.org trixie-security main contrib"

    - name: Add proxmox repo
      ansible.builtin.deb822_repository:
        name: pve
        types: deb
        uris: http://download.proxmox.com/debian/pve
        suites: 'trixie'
        components: pve-no-subscription
        architectures: amd64
        signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg

    - name: Add Ceph repo
      ansible.builtin.deb822_repository:
        name: ceph
        types: deb
        uris: http://download.proxmox.com/debian/ceph-squid
        suites: 'trixie'
        components: no-subscription
        architectures: amd64
        signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg

    - name: apt install microcode
      ansible.builtin.apt:
        name: intel-microcode
        state: present

    - name: apt upgrade dist
      ansible.builtin.apt:
        update_cache: true
        upgrade: "dist"

    - name: apt autoremove
      ansible.builtin.apt:
        autoremove: true

    - name: reboot
      ansible.builtin.reboot:
