---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: '1.11.*'
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: flux-system
      interval: 1h

  install:
    # createNamespace: true
    timeout: 5m

  upgrade:
    timeout: 5m

  values:
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn/"
