---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system

spec:
  interval: 5m
  path: "./clusters/first-cluster/longhorn"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:

    - name: namespaces
      namespace: flux-system

    - name: metallb
      namespace: flux-system
